name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: My Test 1
      id: my-test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: My Test 1
        setup-command: npm install
        command: npm test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MY-TEST-1_RESULTS: "${{steps.my-test-1.outputs.result}}"
      with:
        runners: my-test-1
